export const APP_LOAD = 'APP_LOAD';
export const ADDRESS_LOADING = 'ADDRESS_LOADING';
export const ADDRESS_LOADED = 'ADDRESS_LOADED';
export const ADDRESS_FAILED = 'ADDRESS_FAILED';

export default { 
    APP_LOAD,
    ADDRESS_LOADING, 
    ADDRESS_LOADED,
    ADDRESS_FAILED
 };
